### ISSUE TITLE
[BUGS] Treemap OnHover tooltips freeze after pressed

### ISSUE THREAD

**Issue by HRNPH** [policytracka/policytracka-app#12]
Environment: windows
Browser: Firefox-112.0 (64-bit)
Refer to this PR #11
![image](https://user-images.githubusercontent.com/51855316/232238669-ab21f423-dd73-4642-bdca-9bbab1dffac7.png)
![image](https://user-images.githubusercontent.com/51855316/232238650-11b72f84-5e37-4310-bcdc-8df94e6a2f97.png)

**Comment by ntsd** [comment]
Fix here https://github.com/policytracka/policytracka-app/pull/13
